config/routes.rb
Rails.application.routes.draw do
  get "users/dashboard"
  resources :users do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :audios
  resources :images
  devise_for :users, controllers: {
                       registrations: "registrations",
                     }
  resources :videos
  root "home#index"
  resources :relationships, only: [:create, :destroy]
end

app/models/audio.rb
class Audio < ApplicationRecord
  mount_uploader :file, AudioUploader
  belongs_to :user
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  before_action :set_audio, only: [:show, :edit, :update, :destroy]

  # GET /audios
  # GET /audios.json
  def index
    @audios = Audio.all
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
  end

  # GET /audios/new
  def new
    @audio = current_user.audios.build
  end

  # GET /audios/1/edit
  def edit
  end

  # POST /audios
  # POST /audios.json
  def create
    @audio = current_user.audios.build(audio_params)

    respond_to do |format|
      if @audio.save
        format.html { redirect_to @audio, notice: "Audio was successfully created." }
        format.json { render :show, status: :created, location: @audio }
      else
        format.html { render :new }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audios/1
  # PATCH/PUT /audios/1.json
  def update
    respond_to do |format|
      if @audio.update(audio_params)
        format.html { redirect_to @audio, notice: "Audio was successfully updated." }
        format.json { render :show, status: :ok, location: @audio }
      else
        format.html { render :edit }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @audio.destroy
    respond_to do |format|
      format.html { redirect_to audios_url, notice: "Audio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_audio
    @audio = Audio.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def audio_params
    params.require(:audio).permit(:title, :file)
  end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/views/audios/_audio.html.erb
<p>
  <strong>Title:</strong>
  <%= audio.title %>
</p>
<p>
  <audio controls src="<%= audio.file %>"></audio>
</p>
<p><%= audio.user.email %></p>
<%= link_to 'Edit', edit_audio_path(audio) %>

app/views/audios/_form.html.erb
<%= form_with(model: audio, local: true) do |form| %>
  <% if audio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(audio.errors.count, "error") %> prohibited this audio from being saved:</h2>
      <ul>
        <% audio.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/audios/edit.html.erb
<h1>Editing Audio</h1>

<%= render 'form', audio: @audio %>

<%= link_to 'Show', @audio %> |
<%= link_to 'Back', audios_path %>

app/views/audios/index.html.erb
<h1>Audios</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @audios.each do |audio| %>
      <tr>
        <td><%= audio.title %></td>
        <td>
          <audio controls src="<%= audio.file %>"></audio>
        </td>
        <td><%= link_to audio.user.email, audio.user %></td>
        <td><%= link_to 'Show', audio %></td>
        <td><%= link_to 'Edit', edit_audio_path(audio) %></td>
        <td><%= link_to 'Destroy', audio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Audio', new_audio_path %>

app/views/audios/new.html.erb
<h1>New Audio</h1>

<%= render 'form', audio: @audio %>

<%= link_to 'Back', audios_path %>

app/views/audios/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @audio.title %>
</p>
<p>
  <strong>File:</strong>
  <audio controls src="<%= @audio.file %>"></audio>
</p>
<%= link_to 'Edit', edit_audio_path(@audio) %> |
<%= link_to 'Back', audios_path %>