config/routes.rb
Rails.application.routes.draw do
  get "users/dashboard"
  resources :users do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :audios
  resources :images
  devise_for :users, controllers: {
                       registrations: "registrations",
                     }
  resources :videos
  root "home#index"
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<!--Main Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark scrolling-navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%# <%= image_tag('logo.png', class: "img-fluid logo") %>Zimcreative
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Videos', videos_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Audios', audios_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Images', images_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to 'Profile', current_user, class: "dropdown-item" %>
            <%= link_to 'Dashboard', users_dashboard_path, class: "dropdown-item" %>
            <%= link_to 'Settings', edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav nav-flex-icons">
      <li class="nav-item">
        <a class="nav-link"><i class="fa fa-facebook-f"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><i class="fa fa-twitter"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><i class="fa fa-instagram"></i></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="notification bg-info global-notification p-2 text-light text center">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification bg-warning global-notification p-2 text-light text center">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>